# Generated by Django 3.2.18 on 2023-05-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewimage',
            old_name='post',
            new_name='review',
        ),
    ]
