# Generated by Django 3.2.18 on 2023-05-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cost',
            field=models.CharField(max_length=100),
        ),
    ]
