# Generated by Django 3.2.18 on 2023-05-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_review_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='satisfaction',
            field=models.CharField(max_length=100),
        ),
    ]
